---
# tasks file for shell

- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: "installed"
    update_cache: yes
    cache_valid_time: 86400 
  become: yes
  with_items: "{{ shell_apt_packages }}"

- name: Install pip packages
  pip:
    name: "{{ item }}"
  become: yes
  with_items: "{{ shell_pip_packages }}"

