---
# tasks file for desktop


- name: Install snap packages
  become: yes
  snap:
    name: "{{ desktop_snap_packages }}"
    state: "present"
    classic: yes
  tags:
    - desktop_apt


- name: Install apt packages
  become: yes
  apt:
    name: "{{ desktop_apt_packages }}"
    state: "latest"
    update_cache: yes
  tags:
    - desktop_apt


- name: Install ICA Workspace (Full Package)
  block:

    - name: Check if icaclient is installed
      command: "dpkg-query -l icaclient"
      ignore_errors: true
      changed_when: false
      register: deb_check


    - block:

        - name: Add i386 architecture
          shell: "dpkg --add-architecture i386"
          become: yes
 
        - name: "Apt update"
          shell: "apt update"
          become: yes

        - name: "Download ICA Workspace (Full Package)"
          shell: "wget https://downloads.citrix.com/17780/icaclient_20.04.0.21_amd64.deb?__gda__=1587383602_058ee3cff80139a5f94a99e2f5726c93 -O /tmp/ica.deb"

        - name: "Install ICA Client package"
          shell: "gdebi --n /tmp/ica.deb"
          become: yes

        - shell: "xdg-mime default wfica.desktop application/x-ica"

        - file:
            path: "/tmp/ica.deb"
            state: "absent"
          failed_when: false
          ignore_errors: true
          changed_when: false

      when: deb_check is failed

- name: No image as wallpaper
  include_tasks: change_key_in_all_schemas.yml
  vars:
    filter_key: 'show-desktop-icons'
    keys: 
        - 'picture-filename'
        - 'picture-uri'
    value: ''


- name: Solid color background
  block:
    - include_tasks: change_key_in_all_schemas.yml
      vars:
        filter_key: 'show-desktop-icons'
        keys: 
            - 'color-shading-type'
        value: 'solid'

    - include_tasks: change_key_in_all_schemas.yml
      vars:
        filter_key: 'show-desktop-icons'
        keys: 
            - 'primary-color'
        value: 'rgb(13,21,41)'




