---
# tasks file for desktop

- name: Add Spotify epo
  become: yes
  block:

    - shell: "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0DF731E45CE24F27EEEB1450EFDC8610341D9410"
      changed_when: false

    - lineinfile:
        path: "/etc/apt/sources.list.d/spotify.list"
        line: "deb http://repository.spotify.com stable non-free"
        state: "present"
        create: "yes"





- name: Add Google Chrome Repo
  become: yes
  block:

    - shell: "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -"
      changed_when: false

    - lineinfile:
        path: "/etc/apt/sources.list.d/google.list"
        line: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        state: "present"
        create: "yes"


- name: Install apt packages
  become: yes
  apt:
    name: "{{ item }}"
    state: "installed"
    update_cache: yes
  with_items: "{{ desktop_apt_packages }}"
  tags:
    - desktop_apt


- name: Download and install Skype
  block:
 
    - name: Check if Skype is installed
      command: "dpkg-query -l skypeforlinux"
      ignore_errors: true
      changed_when: false
      register: deb_check


    - block:

        - command: "wget https://repo.skype.com/latest/skypeforlinux-64.deb -O /tmp/skype.deb"
          changed_when: false


        - shell: "gdebi --n /tmp/skype.deb"
          become: yes

        - file:
            path: "/tmp/skype.deb"
            state: "absent"
          failed_when: false
          ignore_errors: true
          changed_when: false

      when: deb_check|failed
 


- name: Install ICA Client
  block:

    - name: Check if Skype is installed
      command: "dpkg-query -l icaclient"
      ignore_errors: true
      changed_when: false
      register: deb_check


    - block:

        - name: Add i386 architecture
          shell: "dpkg --add-architecture i386"
          become: yes
 
        - name: "Apt update"
          shell: "apt update"
          become: yes

        - name: "Download ICA Client package"
          #shell: "wget https://downloads.citrix.com/10837/icaclient_13.2.0.322243_amd64.deb?__gda__=1513034520_164fbc79677546ef2381f5c8ca9b2509 -O /tmp/ica.deb"
          shell: "wget https://downloads.citrix.com/14076/icaclient_13.8.0.10299729_amd64.deb?__gda__=1513036518_425183023a12ce3b1334d46a489d1d01 -O /tmp/ica.deb"

        - name: "Install ICA Client package"
          shell: "gdebi --n /tmp/ica.deb"
          become: yes

        - shell: "ln -s /usr/share/ca-certificates/mozilla/* /opt/Citrix/ICAClient/keystore/cacerts/"
          become: yes

        - shell: "c_rehash /opt/Citrix/ICAClient/keystore/cacerts/"
          become: yes

        - shell: "xdg-mime default wfica.desktop application/x-ica"

        - file:
            path: "/tmp/ica.deb"
            state: "absent"
          failed_when: false
          ignore_errors: true
          changed_when: false

      when: deb_check|failed

- name: No image as wallpaper
  include_tasks: change_key_in_all_schemas.yml
  vars:
    filter_key: 'show-desktop-icons'
    keys: 
        - 'picture-filename'
        - 'picture-uri'
    value: ''


- name: Solid color background
  block:
    - include_tasks: change_key_in_all_schemas.yml
      vars:
        filter_key: 'show-desktop-icons'
        keys: 
            - 'color-shading-type'
        value: 'solid'

    - include_tasks: change_key_in_all_schemas.yml
      vars:
        filter_key: 'show-desktop-icons'
        keys: 
            - 'primary-color'
        value: 'rgb(13,21,41)'




